[pyprland]

plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.spotify]
animation = "fromBottom"
command = "spotify"
class = "Spotify"
size = "90% 90%"
